### ISSUE TITLE
初回のSendEventが受信側で無視される

### ISSUE THREAD

**Issue by llaser** [tutinoco/SimpleNetworkUdonBehaviour#1]
ワールドインスタンスで一度も`SendEvent`が実行されていない場合、初めて実行した`SendEvent`が受信側で無視されます。(VRChat Build 1277)

ワールドに後からjoinした際に、Join以前に送られた`_cmds`の値を無視する想定で`isIgnoredInitSync`による制御を行っていると推察しますが、一度も同期が行われていなかった場合は`isIgnoredInitSync`が`false`のままになってしまうため、初回の`SendEvent`による`_cmds`の変更が無視されます。

以下のように、masterの`OnPlayerJoined`で制御することを提案します
```
public override void OnPlayerJoined(VRCPlayerApi player)
{
    if (player.isMaster) isIgnoredInitSync = true;
}
```
Build 1277で確認したところjoin時のイベント順は以下のようでした。そのためmasterの`OnPlayerJoined`で処理するとplayerが操作可能になるまでの`_cmds`の変更を無視できるようになると思います。
- (ロード画面中)`Start` 
- (暗転後)`OnPlayerJoined(localPlayer)`
- (1フレーム)
- join前の最新値の処理(`OnDeserialization`等)
- ロード中に受信した値の処理(`OnDeserialization`等)
- `OnPlayerJoined(remotePlayer)`

ただし、VRChatのバージョンアップでこのあたりの挙動が変わる可能性があることと、現状はLateJoinerが読み込み中にワールドインスタンス内で`SendEvent`が実行された場合、読み込み直後にその分の`ExecuteEvents`が実行されますが、それがなくなることはご留意ください。

**Comment by tutinoco** [comment]
問題の報告ありがとうございます！
ご指摘いただいた問題ですが、実は認識していた問題でして、修正中でございました。

`OnPlayerJoind`を利用した制御も考えていたのですが
利用者さんがサブクラスで`OnPlayerJoind`をオーバーライドした際に
スーパークラスのメソッドの呼び出しを忘れてしまうと（おっちょこちょいかもですが）
挙動がおかしくなってしまうことを懸念し、利用しないで実現する方法を試しておりました。

`OnPreSerialization`とかも、同じ問題が起こっちゃうのですが
このスーパークラスの目的がNetworkingのラッピングなので、`OnPreSerialization`などの
ネットワークに関するメソッドを利用者さんが使わなくてよくなることも目的としていたこと、そして
なんとなく`OnPlayerJoind`はサブクラスで利用頻度が高そうだったため、避けておりました。

`OnPlayerJoind`を利用せずにこの問題をどのように解消するか考えていたところ
そもそもJoin時に直前の値が同期されることは、便利なことなのではないか？
と思いつきまして、現在は`SimpleNetworkInit`メソッドで初期化して使っていただく仕様に
変更することを検討しています。

```C#
        public void SimpleNetworkInit( bool _ignoreJoinSync )
        {
            isInitialized = true;
            ignoreJoinSync = _ignoreJoinSync;
    
            if( ignoreJoinSync && Networking.IsMaster ) SendEvent("__ignoreJoinSync__");
        }
```

上記コードは一部なので、わかりにくいかもしれませんが
現在この方法を使って問題の解決ができるかどうかテストワールドを作成して実験しているところです:)

Join時のイベント順に関してですが、こちら全く認識していないことだったので参考になりました！
OnPlayerJoindが呼ばれた時には、だいぶ時間が経ってるな...と感じていたので、その疑問が明確に晴れました。
ありがとうございます！

近日中にVector3などの値の送受信にも対応（stringに変換して受信時に戻すだけですが）した新しいバージョンをコミットする予定です！
